### ISSUE TITLE
German umlaut crashes generator

### ISSUE THREAD

**Issue by baldo** [bleeptrack/36c3-generator#1]
I'm using Firefox 70.0.1.

When typing e.g. `möp` into (1) it crashes the generator and the tab freezes. I have to close the tab and re-open it to be able to use the generator again.

There is no exception or error message in the console.

**Comment by baldo** [comment]
Same goes for some other characters, e.g. `~` and `§`. My guess is this occurs when entering a character not included in the font.

**Comment by fes0j** [comment]
Same with Chromium Version 78. I think, the font blackout just doen't has Umlaut glyphs.
Now we need to figure out, how to handle this :-)
