### ISSUE TITLE
einfärben von objekten

### ISSUE THREAD

**Issue by DO1JLR** [bleeptrack/36c3-generator#12]
Hi

Beim Spielen mit dem Generator habe ich manchmal das phänomen, das sich Objekte einfärben. *(siehe Bild*).

![grafik](https://user-images.githubusercontent.com/16953664/70994128-c8f36400-20cd-11ea-8a7d-809fece059e9.png)

Ist das ein beabsichtigtes Feature oder nicht?
Und falls das beabsichtigt ist... Wären die Farbwerte für uns als Team C3SIGN ganz interessant!

Danke :heart:

**Comment by bleeptrack** [comment]
Huhu!
wenn bunte Elemente entstehen, dann ist was kaputt gegangen :D sollte also nicht auftreten, Pfade sind aber komplex und da hat es wohl irgend einen Edge-Case erwischt. Die werden bunt damit ich einen schnellen visuellen Indikator habe, dass was nicht passt. Am einfachsten die Simulation nochmal laufen lassen. Meinstens tritt das bei sehr filigranen Formen oder CompundPaths auf.

**Comment by DO1JLR** [comment]
Danke :heart:
