### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TimDaub** [bleeptrack/36c3-generator#15]
👋,

 I'd like to grow plants in other gardens too.
But I'm not sure I'm allowed to. Please let me know 🕊️

**Comment by DO1JLR** [comment]
Based on the wiki, it is under the [tuwat you want, but think about the omen](https://www.youtube.com/watch?v=b-_wE0mJU5Y) License:

-> [CCC Wiki 36c3](https://events.ccc.de/congress/2019/wiki/index.php/Static:Design)

**Comment by bleeptrack** [comment]
Woops, forgot to answer before closing. 
@TimDaub With "tuwat you want, but think about the omen" License you are free to use it for whatever you like. Mentioning my name or this repo would be nice but is not necessary. Have fun!
@DO1JLR Thanks for taking care :)

**Comment by DO1JLR** [comment]
You're welcome :kissing_heart:
