### ISSUE TITLE
Overlapping labels for "small" window widths

### ISSUE THREAD

**Issue by blinry** [bleeptrack/36c3-generator#2]
In current versions of Firefox and Chromium, when the window is too small, I get overlapping labels, like this:

![screenshot-2019-11-21_22:54:00](https://user-images.githubusercontent.com/81277/69380200-36b89580-0cb2-11ea-8e52-f4f06a111177.png)

Experimentally, this seems to happen for windows with a width of less than 2200 px. :D

**Comment by bleeptrack** [comment]
fixed with commit fda6283a8fd6ba3717caa3c59adca837960e3121 :)
