### ISSUE TITLE
Provide reset button for uploaded SVG files

### ISSUE THREAD

**Issue by blinry** [bleeptrack/36c3-generator#4]
Feature request: when uploading an SVG, and the way it breaks isn't aesthetically pleasing, I'd like to be able to click a button to try again, instead of selecting the SVG file again. Maybe a ">" button like the one after the text box would work?

**Comment by bleeptrack** [comment]
Yeah, also had this on my feature list! Will implement this as soon as there's time :)

**Comment by bleeptrack** [comment]
feature implemented in commit  00c5246a400614b22240547fe1b1c6ace59b4c62 :)
