### ISSUE TITLE
Dynamically update page title

### ISSUE THREAD

**Issue by lucaswerkmeister** [bleeptrack/36c3-generator#5]
I’m currently using Firefox’s screenshot tool to take images of the generated logos, rather than using the “save PNG” feature, because I prefer the black background (and the extra flexibility in choosing the area). For this, it would be useful if the page title was automatically updated to reflect the text (and caption?) when it changes, so that it can be included in the screenshot name, rather than having a bunch of “Screenshot 36c3 Generator(1)”, “(2)” etc. files.

I imagine this would also be useful when using the “share” feature, making it easier to distinguish the permalinks in your browsing history.

I’m not sure what the title should do when the user uploads an SVG, though. Revert back to just “36c3 Generator”, I guess?

**Comment by bleeptrack** [comment]
feature added with commit e0fcc5dc91dadb7f7e1261ccec8edf915799949e :)

**Comment by lucaswerkmeister** [comment]
Thank you <3
